### ISSUE TITLE
Ezreal

### ISSUE THREAD

**Issue by wfzyx** [coldAmphibian/Defense-of-the-Legends#24]
- [x] Missing particles
- [ ] Missing VO
- [ ] Missing SFX
- [x] Missing Card/portrait
- [ ] Missing Ult minimap icon
- [ ] fix scale model
- [ ] fix unit scaling (spell range, projectile speeds)
- [x] Adds AP/AD Scaling
- [ ] set cast points and attack swing

**Comment by wfzyx** [comment]
@Zarthbenn @coldAmphibian any of you guys can please replace the current card/portrait with the default skin static one? just to keep parity with other champions.

**Comment by Zarthbenn** [comment]
Il get on it, im working on a commit with some stuff right now and il add that to it

**Comment by Numbers11** [comment]
I feel like his animations need to be sped up a bit, especially the ultimate. Maybe there is a constant factor by which his animations should be faster.
Also Castanimations arent really useful to play the animations since they require a long enough cast point to be visible.
I am not exactly sure how lols behaviour is on this , but it might be better to have an OnAbilityPhaseStart event that calls a Lua script which plays the selected animation with StartGesture()

**Comment by wfzyx** [comment]
I've just added animations.lua to maybe help with these kind of things.

I'm not exactly sure how this will be handled tho.

Basic behaviors like AA reset, animation canceling etc idk exactly how will be handled

**Comment by wfzyx** [comment]
Archived
