### ISSUE TITLE
Mundo

### ISSUE THREAD

**Issue by wn-mitch** [coldAmphibian/Defense-of-the-Legends#28]
- [ ] Missing Particles
- [ ] Missing VO
- [ ] Missing SFX
- [ ] Missing Card/Portrait
- [ ] Missing Model

welp

**Comment by Zarthbenn** [comment]
Il make the portrait. If I recall correctly you were working on the model, did you hit an error?

**Comment by wn-mitch** [comment]
Yeah, I'm still hitting errors trying to pull his base model.

**Comment by Zarthbenn** [comment]
I can probably help you out if you post what specific errors youre getting, but if you want I can just import it myself it since that might be easier. Your choice

**Comment by wn-mitch** [comment]
http://i.gyazo.com/8dfea86f5d5800e102afccdd01253d7a.png

This is what's getting tossed when I try to extract the base .dds

**Comment by Zarthbenn** [comment]
Strange, thats something that should be passed on the dev. Either way what you are extracting is the loadscreen splash image, you want DrMundo.dds which for some reason I cant find in your image. 

Here is what mine looks like http://gyazo.com/79584f257c87f6978edc8e85f4020fe1

I took the liberty of extracting the dds here http://i.imgur.com/CaRX6NG.png

**Comment by wn-mitch** [comment]
My extract of the League folder is failing at some point as well, idk why. I feel like I'm pushing too much onto you guys :p

**Comment by Zarthbenn** [comment]
If you're getting an error about a duplicate version turret_chaos or something similar I have been getting that aswell. Dont worry about pushing, all of this needs to get done eventually.

**Comment by wn-mitch** [comment]
It stalls at this point: http://i.gyazo.com/5119783f55d17a6b614a0963edd89a38.png

I might need to repair my installation

**Comment by coldAmphibian** [comment]
the program doesn't tell you if it finishes loading
swap to the console and type "help"

**Comment by coldAmphibian** [comment]
if that works, it's finished. Also, if it complains about duplicate versions of the same file or unpaired rafs, that's LoL updating badly. It doesn't remove old files when it updates, it just doesn't use them. My first LoL install is like 12gb because of this XD

**Comment by vs49688** [comment]
Yeah, I've fixed that, the current git tells you whether or not it's completed ^_^

As for the "Map failed" error, that happens when the JVM either can't map the file into memory for access, or has run out of memory. Methinks a corrupted RAF. Embedded files in RAFs are compressed, thus their (actual) size cannot be determined until actually extracted. If the DEFLATE stream is corrupt, it might just keep going until it runs out of memory, which would cause a Map failed. If you could track down the offending RAF/RAF.DAT pair and upload it somewhere I would be grateful.

Also, if you come across issues like this, I would appreciate it if you reported them on the bug tracker (https://github.com/vs49688/raftools/issues). It'll enable me to fix them faster (the only reason I saw this was because @coldAmphibian messaged me about it).

**Comment by wfzyx** [comment]
Archived
