### ISSUE TITLE
Custom drawings off place

### ISSUE THREAD

**Issue by wfzyx** [coldAmphibian/Defense-of-the-Legends#32]
@Capruce I saw veigar and lux custom circle stuff, pretty good job.

Mechanically speaking they look good (not tested too much), but idk if it's aspect ratio or resolution difference it makes, the green circle to be draw in the wrong place (aside from the effect being correct)

![image](https://cloud.githubusercontent.com/assets/5880370/8886919/8cdf3cfa-3248-11e5-92d5-b0702b377f58.png)

![image](https://cloud.githubusercontent.com/assets/5880370/8886922/931a7db4-3248-11e5-89d5-3bfd560a3c22.png)

**Comment by Capruce** [comment]
Yeah I think it has to do with the circle not being drawn on the ground
(not confirmed) I get a sense of them being off as well. I figured since
its just placeholder it wouldn't matter too much.

EDIT: Oh wait just properly saw your image. That's never happened before...they should have to be on the doughnut bit to be stunned. Does it always happen?

**Comment by wfzyx** [comment]
Yeap 100% reliable happens, the effect is happening on the right place, but the place holder is offset always to left/top

**Comment by Capruce** [comment]
Weird I look into it tomorrow since its pretty late here right now :) I
changed it a bit anyway to work without the use of self.

**Comment by coldAmphibian** [comment]
could you get them to be drawn as a texture? i have no idea how you're doing it atm. I can get you the LoL crosshairs if you wanted to

**Comment by Zarthbenn** [comment]
its a placeholder particle not indicator

**Comment by coldAmphibian** [comment]
awww

**Comment by wfzyx** [comment]
Archived
